apiVersion: v1
kind: Pod
metadata:
  name: p3
  namespace: staging
  labels:
    app.kubernetes.io/name: hello
spec:
  restartPolicy: Never
  containers:
  - name: hello
    image: vincentstark/9spokes-challenge:latest
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
    ports:
    - containerPort: 8080
  initContainers:
  - name: init-hello
    image: busybox
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
    command:
      - cat
      - /app/ready.txt