apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: staging
  labels:
    app.kubernetes.io/name: hello
spec:
  containers:
  - name: hello
    image: vincentstark/9spokes-challenge:latest
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /doesntmatter
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5